import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./lib/QueryClientProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased p-layout p-silver-100`}
      >
        <Header />
        <div className="pt-16">
          <QueryProvider>
            {children}
          </QueryProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
